# docker-compose.dev.yml - Development setup with just database
# Use this for Phase 1.1 development - run the API locally

services:
  postgres:
    image: postgres:15-alpine
    container_name: design_agent_postgres_dev
    environment:
      POSTGRES_DB: design_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local