# docker-compose.yml - Design Research Agent v1.2

services:
  postgres:
    image: postgres:15-alpine
    container_name: design_agent_postgres
    environment:
      POSTGRES_DB: design_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # For Phase 1.1, we'll start with just PostgreSQL
  # Redis will be added in later phases for caching
  # redis:
  #   image: redis:7-alpine
  #   container_name: design_agent_redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5
  #   restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local